### ISSUE TITLE
Problem with same name of parent directory

### ISSUE THREAD

**Issue by awallat** [francescou/docker-compose-ui#103]
My docker-structure is something like this:

>project1
>>  qs
    test
    prod

>project2
>>    qs
    test
    prod

In "qs" of project1 and project2 is a docker-compose.yml file, but only the first one is found. It seems that the direct parent only is used for the identifier. I also tried symbolic links to keep my original structure and collect my project files in a separate structure, which would be correctly recognized by docker-compose-ui, but it seems that those links are not followed.

I'm under Windows 10 by the way.

**Comment by francescou** [comment]
please make sure that symbolic links are preserved (see https://stackoverflow.com/a/40322275)
