### ISSUE TITLE
Add support for .yaml

### ISSUE THREAD

**Issue by droogmic** [francescou/docker-compose-ui#104]
Docker-compose is agnostic to docker-compose file extensions being .yml or .yaml
[Docker-compose code reference](https://github.com/docker/compose/blob/ddbc9e30b0608ebdacb333f56f2519a4e26d4db6/compose/config/config.py#L141)

Please support the less common docker-compose.yaml in the same way. Currently projects with only a docker-compose.yaml file are not detected.

Minor issue to fix, harder to identify why projects are not detected.

**Comment by francescou** [comment]
.yaml extension is now supported in `francescou/docker-compose-ui:latest`, feedback is welcome

**Comment by droogmic** [comment]
Thanks for the quick update

**Comment by francescou** [comment]
I've released the fix in `francescou/docker-compose-ui:1.10.1`.
I'm closing this issue for now, feel free to reopen if necessary.
