### ISSUE TITLE
Doesn't work on Red Hat Enterprise Linux Server 7.4

### ISSUE THREAD

**Issue by maxt** [francescou/docker-compose-ui#105]
Hello! I tried to use it on RHEL 7.4 and it doesn't work.
It runs without any errors but I can't see my project.
Configuration the same as I have on my SLES machine, hovewer I modified run command to avoid problems with selinux. Here is my modified run command which I put inside docker-compose-ui.sh: 
`docker run -d  --name docker-compose-ui -v $(pwd):$(pwd):Z -w $(dirname $(pwd)) -p 8080:5000 -v /var/run/docker.sock:/var/run/docker.sock:Z afx.artapp/docker-compose-ui:latest`

```
[julia@ibfx qe]$ ./docker-compose-ui.sh
INFO:root:docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
INFO:root:{'qe': '/home/julia/./qe'}
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

```
[julia@ibfx qe]$ echo $PWD
/home/julia/qe
[julia@ibfx qe]$ ls -al
total 12
drwxrwxrwx. 4 julia julia   98 Apr 19 11:24 .
drwx------. 4 julia julia  166 Apr 19 11:15 ..
-rwxrwxrwx. 1 julia julia  185 Apr 19 11:24 docker-compose-ui.sh
-rwxrwxrwx. 1 julia julia 1313 Apr 19 10:06 docker-compose.yml
-rw-rw-r--. 1 julia julia   23 Apr 19 10:21 .env
drwxrwxrwx. 2 julia julia   50 Apr 19 10:05 feeder
drwxrwxr-x. 8 julia julia  198 Apr 19 11:19 .git

```

`

**Comment by francescou** [comment]
Hi @maxt 

the log line `INFO:root:{'qe': '/home/julia/./qe'}` tells us that the project `/home/julia/qe/docker-compose.yml` has been found.

You should see a "qe" entry on the left column. If not, could you please share the output of <http://localhost:8080/api/v1/projects> ? thanks.

**Comment by maxt** [comment]
`docker exception: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.25, server API version: 1.24)")`

Got it. I'm trying to update my docker installation right now. 

Works perfectly well after update. Thank you!
