### ISSUE TITLE
[Enhancement] Edit docker-compose file for existing services

### ISSUE THREAD

**Issue by dchidell** [francescou/docker-compose-ui#107]
The ability to clone services is great, as these can be edited in-browser, saved and run. However for existing services there is no way (that I can see) to modify the compose file and re-'up' the service to apply changes made to containers within the service.

Can the functionality of editing a cloned service be extended to allow for editing of existing services?

**Comment by MichaelMackus** [comment]
Technically this should be possible, since clone already includes the existing env & docker-compose (from what I remember). I'd just have to add the endpoint to "update" an existing project (assuming that functionality doesn't exist).

**Comment by francescou** [comment]
When you say existing services you're referring to externally managed docker-compose projects, right?

If so, I think it would be pretty difficult to clone a running project since there is no way to create a docker-compose.yml file from a bunch of running containers.

**Comment by dchidell** [comment]
Sorry I think I may have confused the issue by mentioning clone.

Essentially what I am trying to do is simply edit the compose file for an existing service within the UI.

**Comment by francescou** [comment]
Sorry for the misunderstanding, I've implemented this feature and it is now available using `francescou/docker-compose-ui:latest`

I am now testing it and it should be included in the next release in the upcoming days.

**Comment by dchidell** [comment]
I've tested this on the latest release and looks good! There's a small cosmetic issue that the message displayed in the bottom right displays 'created project' rather than 'updated project', but functionality wise I can't see any issues. Thanks for implementing this so quickly!

**Comment by francescou** [comment]
the feature has been released in francescou/docker-compose-ui:1.13.0 (I've corrected the message as well)

**Comment by francescou** [comment]
I'm closing this issue, feel free to reopen if necessary.
