### ISSUE TITLE
does not work for docker 1.9 and docker-compose 1.5

### ISSUE THREAD

**Issue by ymote** [francescou/docker-compose-ui#11]
Tried to start the simple wordpress project and got the following error. Does the project support Docker 1.9 and docker-compose 1.5? Thanks.

error: argument 2 to map() must support iteration

Here is the wordpress YAML file

wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 80

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root

Here is the docker version info.

Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   087e245
 Built:  
 OS/Arch:      linux/amd64

**Comment by francescou** [comment]
I've tried docker compose ui with the 1.5 RC docker compose some weeks ago and there were some issues due to breaking changes.

I will fix them in the next days

**Comment by ymote** [comment]
thanks so much

**Comment by francescou** [comment]
commit ee716425dd0eed89646aef94ae77536ccd8a2ccf should have fixed the issue.

**Comment by ymote** [comment]
Thanks. Basic functions work. But when list the project status I still get the following error. 

error: argument 2 to map() must support iteration

**Comment by francescou** [comment]
can you please give me the full stack trace error? thanks

**Comment by ymote** [comment]
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/6eba0667b420465f326b0d98fdd47957b7cc2d3353586e14f878b03dc9defd14/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/77b0f3e9bd431b3c245c1e0260a17243a6b96bbd5b4bca3a9680243e5ce4bf0a/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Drocketchat%22%2C+%22com.docker.compose.oneoff%3DTrue%22%5D%7D&size=0 HTTP/1.1" 200 3
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/6eba0667b420465f326b0d98fdd47957b7cc2d3353586e14f878b03dc9defd14/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/6eba0667b420465f326b0d98fdd47957b7cc2d3353586e14f878b03dc9defd14/json HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/main.py", line 54, in project_containers
    containers = ps_(project)
  File "/app/scripts/bridge.py", line 26, in ps_
    'is_running': container.is_running}, containers)
  File "/app/scripts/bridge.py", line 25, in <lambda>
    'volumes': get_volumes(get_container_from_id(project.client, container.id)),
  File "/app/scripts/bridge.py", line 46, in get_volumes
    volumes)
TypeError: argument 2 to map() must support iteration
INFO:werkzeug:24.130.95.106 - - [21/Nov/2015 04:38:03] "GET /api/v1/projects/Rocket.Chat HTTP/1.1" 500 -

**Comment by francescou** [comment]
I can't reproduce the issue, could you please try to run the demo projects (e.g. volumes-demo) and see if you get th error?

otherwise, can you send me your docker-compose.yml file? thanks

**Comment by ymote** [comment]
Here is the log

INFO:werkzeug:24.130.95.106 - - [21/Nov/2015 09:58:38] "GET /api/v1/projects/docker-compose-nodejs-examples HTTP/1.1" 500 -
DEBUG:root:get project /opt/docker-compose-projects/volumes-demo
DEBUG:compose.config.config:Using configuration files: /opt/docker-compose-projects/volumes-demo/docker-compose.yml
DEBUG:docker.auth.auth:Trying /root/.docker/config.json
DEBUG:docker.auth.auth:File doesn't exist
DEBUG:docker.auth.auth:Trying /root/.dockercfg
DEBUG:docker.auth.auth:File doesn't exist - returning empty config
DEBUG:root:ps volumesdemo
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): salt.appchef.io
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dvolumesdemo%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 1547
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/28866d2333b40f1060eefde9c134bf6bcc3fa627a6ed1878b11c1c951596530d/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/9ae5f7a41940cb1cf0c46fc4cc33987862747219ece6b551518f60bce0f2d712/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dvolumesdemo%22%2C+%22com.docker.compose.oneoff%3DTrue%22%5D%7D&size=0 HTTP/1.1" 200 3
INFO:werkzeug:24.130.95.106 - - [21/Nov/2015 09:58:41] "GET /api/v1/host HTTP/1.1" 200 -
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/28866d2333b40f1060eefde9c134bf6bcc3fa627a6ed1878b11c1c951596530d/json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.19/containers/28866d2333b40f1060eefde9c134bf6bcc3fa627a6ed1878b11c1c951596530d/json HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/main.py", line 54, in project_containers
    containers = ps_(project)
  File "/app/scripts/bridge.py", line 26, in ps_
    'is_running': container.is_running}, containers)
  File "/app/scripts/bridge.py", line 25, in <lambda>
    'volumes': get_volumes(get_container_from_id(project.client, container.id)),
  File "/app/scripts/bridge.py", line 46, in get_volumes
    volumes)
TypeError: argument 2 to map() must support iteration

**Comment by francescou** [comment]
I guess the issue is related with the usage of Docker Swarm.

I will setup a Swarm environment ASAP and I'll test Docker Compose UI on it.

sorry for the inconvenience.
