### ISSUE TITLE
Is the docker-compose-ui project dead?

### ISSUE THREAD

**Issue by nsano-rururu** [francescou/docker-compose-ui#120]
If development is over
When you archive, you can see that it is read-only and is not maintained.

Archiving a GitHub repository
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository

**Comment by binarymist** [comment]
Or, possibly look at allowing a select person or persons privileges to continue to manage this repository. Failing that, a concensus for an ordained fork may be the way forward?

**Comment by nsano-rururu** [comment]
I think I have no choice but to continue maintenance with the forked repository.
