### ISSUE TITLE
When I build the project, how to turn off the cache?

### ISSUE THREAD

**Issue by lisicongIBM** [francescou/docker-compose-ui#13]
When I build the project, how to turn off the cache?

**Comment by francescou** [comment]
Hi, I've added an option to configure **pull** and **no_cache** build parameters, see documentation [here](http://francescou.github.io/docker-compose-ui/api.html#docker-compose-build-of-project-hello-node-with-params-pull-and-nocache)

**Comment by lisicongIBM** [comment]
Thanks！
