### ISSUE TITLE
Hardcoded dir details

### ISSUE THREAD

**Issue by mkscala** [francescou/docker-compose-ui#2]
for uploading my own demo projects should we use the folder structure exactly the below?
can't i use my own path: /Users/<anyname>/docker-compose-ui/demo-projects ?

/home/user/docker-compose-ui/demo-projects

If I give my own path getting the below error
no projects configured, please run the container with the option
-v /home/user/docker-compose-ui/demo-projects:/opt/docker-compose-projects:ro

the command i ran
docker run --name docker-compose-ui -p 5000:5000 -v /Users/mkscala/docker-compose-ui/demo-projects:/opt/docker-compose-projects:ro -v /var/run/docker.sock:/var/run/docker.sock francescou/docker-compose-ui

**Comment by francescou** [comment]
you should be able to mount any directory you want, as long you mount it to /opt/docker-compose-projects so the command you ran is correct

could you pleasa tell me what is the output of 

docker exec docker-compose-ui ls -l /opt/docker-compose-projects/

**Comment by mkscala** [comment]
/Users/mkmani/datalabapi/kafkalab0 (folder i need to mount to Container)
LM-SJN-00873037:kafkalab0 mkmani$ ls -tlra 
total 8
-rw-r--r--  1 mkmani  100046058  289 Aug  7 16:24 docker-compose-single-broker.yml
drwxr-xr-x  8 mkmani  100046058  272 Aug  7 19:37 ..
drwxr-xr-x  3 mkmani  100046058  102 Aug  7 19:37 .

the output of docker exec docker-compose-ui ls -l /opt/docker-compose-projects/
LM-SJN-00873037:~ mkmani$ docker exec docker-compose-ui ls -l /opt/docker-compose-projects/
total 4
-rw-r--r-- 1 1000 staff 289 Aug  7 23:24 docker-compose-single-broker.yml

**Comment by mkscala** [comment]
error i get in the Docker UI 
Projects
no projects configured, please run the container with the option
-v /home/user/docker-compose-ui/demo-projects:/opt/docker-compose-projects:ro

**Comment by mkscala** [comment]
WebServer running in DockerContainer 
LM-SJN-00873037:kafkalab0 mkmani$ docker run --name docker-compose-ui -p 5000:5000 -v /Users/mkmani/datalabapi/kafkalab0:/opt/docker-compose-projects:ro -v /var/run/docker.sock:/var/run/docker.sock francescou/docker-compose-ui
DEBUG:root:{}
INFO:werkzeug: \* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:werkzeug: \* Restarting with stat
DEBUG:root:{}

**Comment by mkscala** [comment]
I guess I fixed it need to rename the .yml file from docker-compose-single-broker.yml to docker-compose.yml

**Comment by francescou** [comment]
yes you're right, as you can see only docker-compose.yml are listed as projects: https://github.com/francescou/docker-compose-ui/blob/master/scripts/find_yml.py#L14

if you want to manage more docker-compose.yml files I suggest you to put them in different folder and give each folder a meaningful name for the project, (like I did for demo projects: https://github.com/francescou/docker-compose-ui/tree/master/demo-projects
