### ISSUE TITLE
how to request a composeregistry.com token?

### ISSUE THREAD

**Issue by yowenter** [francescou/docker-compose-ui#21]
Hi,
Nice project,Much appreciation for your done!

I tried to request a  composeregistry.com api token ,but no response for a long time .
Could U send  me an api token ?
Here is my email :  wenter.wu@gmail.com .
Much thanks. :+1:

**Comment by francescou** [comment]
Hi, I've sent an API key to your email address right now,

sorry for the delay

I'm closing the issue, feel free to reopen if needed.

Francesco
