### ISSUE TITLE
Logs unification

### ISSUE THREAD

**Issue by dvdred** [francescou/docker-compose-ui#3]
Hello Francesco, this ui is very clean an useful, thank you!
I have a request: I wish the vision of the logs returned as it was in previous versions, when the logs of all containers were viewed simultaneously in the same window. Do you think is possible?

**Comment by francescou** [comment]
Ciao David,

I think that this can be really useful for lots of use cases.
I am currently on vacation, I will add a new panel with aggregated logs when I will be back!

**Comment by dvdred** [comment]
Great job, it works clean for me!
