### ISSUE TITLE
Add auto refresh + Auto scroll on log view

### ISSUE THREAD

**Issue by WTFKr0** [francescou/docker-compose-ui#33]
Is that possible ?

Thanx

**Comment by francescou** [comment]
it would be nice to have something like this with SSE/websockets... (see #14)

the alternative would be polling an HTTP service

I'll try to find a solution

**Comment by francescou** [comment]
Hi, I've implemented a prototype of auto refresh, see branch [logs-auto-refresh](https://github.com/francescou/docker-compose-ui/tree/logs-auto-refresh).

It would be great If you could help me testing it, thanks!

**Comment by WTFKr0** [comment]
OK I'm on that branch now
It seems to work well

Things I noted : 
- The log must refresh and scroll bottom when the user click on view logs, not after 4 sec the first time
- We should add a button to stop manually the refresh, like a checkbox "autorefresh" on/off
- A clear button to clear current log and just show the log for now if it is possible
- Maybe the 4 sec interval can be adjustable

Thanx, I continue to test it

**Comment by WTFKr0** [comment]
Also maybe : 
- Enable auto refresh when user scroll to bottom
- Disable auto refresh when user scroll out of bottom
- Add option to autowrap lines (for long log lines)
- Add same functionalities to log of unique container
