### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by filipeguelber** [francescou/docker-compose-ui#36]
Is it possible to provide a secure access to UI, via login for eg ?

**Comment by francescou** [comment]
I think you have two options: you could either use a reverse proxy (e.g. nginx) and configure basic http authentication (see [this guide](https://gist.github.com/francescou/9ad531c91adcbfaaa21ff48d5d0c0b7d)) or if you need a graphical login screen you can do something like @dalareo did  https://github.com/francescou/docker-compose-ui/issues/25#issuecomment-213564231

**Comment by francescou** [comment]
I'm closing the issue for now, please feel free to reopen it if necessary
