### ISSUE TITLE
Too many projects

### ISSUE THREAD

**Issue by WTFKr0** [francescou/docker-compose-ui#38]
Hi

Can we found an elegant way to manage many projects
I test with 50 projects, and i see two things
- Maybe a pagination (like max 10 projects) will be fine
- The search filter must be placed on top of project list

Do you agree ?

Thx

**Comment by WTFKr0** [comment]
PR : #39

**Comment by francescou** [comment]
merged PR #39 thank you!

I will test projects client-side pagination ASAP.

**Comment by WTFKr0** [comment]
Thanx to you

**Comment by francescou** [comment]
fixed in 1586b67f1b665fbea2557bcfa8e34b2e720b072a
