### ISSUE TITLE
Add some labels / images to projects

### ISSUE THREAD

**Issue by WTFKr0** [francescou/docker-compose-ui#40]
Hi !

WDYT about adding some colour label or png images/logos to projects
These labels/logos can then appear on the left of the project list

Thanx

**Comment by francescou** [comment]
Hi,

even if it could be a nice feature I can't figure out a simple way to define an association between a project and its icon.

a solution could be to have an "icon.png" in the folder containing the docker-compose.yml file but there are two problems: the icon should be really small (16x16 px) and it should be checked (server side) the existence of the icon file for each project.

do you have a better solution for this?

**Comment by WTFKr0** [comment]
No

I think the icon.png file is a good option
we can resize image on client side to force the size
For each project, if a icon.png file is present, add a img html tag with content in base64 maybe ?

The same process can be done with a labels.json file for example like that : 

```
{
   "label1":"blue",
   "label2":"red"
}
```

WDYT ?
Thanx

**Comment by WTFKr0** [comment]
Work on logos here : #42

**Comment by francescou** [comment]
merged, thanks!

**Comment by francescou** [comment]
released in [francescou/docker-compose-ui:0.20.1](https://github.com/francescou/docker-compose-ui/releases/tag/v0.20.1)
