### ISSUE TITLE
Missing image info (name and version) for each container

### ISSUE THREAD

**Issue by liyaka** [francescou/docker-compose-ui#44]
I believe it should appear in container details

**Comment by liyaka** [comment]
Thanks! Is there a version released with this change?

**Comment by francescou** [comment]
Hi, I plan to release a new version in the next days, meanwhile you could use `francescou/docker-compose-ui:latest`

**Comment by liyaka** [comment]
Thanks!

**Comment by francescou** [comment]
released [francescou/docker-compose-ui:0.20.1](https://github.com/francescou/docker-compose-ui/releases/tag/v0.20.1)
