### ISSUE TITLE
edit yml

### ISSUE THREAD

**Issue by DocMAX** [francescou/docker-compose-ui#47]
i dont see any option to edit yml file after its created...

**Comment by francescou** [comment]
Hi,

there is no option to do so at the moment.

if you want, you could store your docker compose project on a git repository (github/gitlab) and run the application with the env [GIT_REPO](https://github.com/francescou/docker-compose-ui#load-projects-from-a-git-repository-experimental)

this way you can edit the yml files from the github interface and then reload the project from _docker-compose-ui_ using **Reload projects**
