### ISSUE TITLE
Scale command doesn't do anything

### ISSUE THREAD

**Issue by liyaka** [francescou/docker-compose-ui#48]
I have several containers defined in compose file, and it works great with compose-ui.
When I press on "scale" button on a container, the page is refreshed but nothing happens.
If I run from command line on the machine:
docker-compose scale worker=2
it runs the second worker container and i can see it in UI.
Is there logs i can see in docker-compose-ui? What is missing?
Please advise.
Thank you

**Comment by francescou** [comment]
Hi,
I've tested docker-compose-ui:

**Comment by francescou** [comment]
Hi,
I've tested `francescou/docker-compose-ui:0.20.1` on Chromium 52 and Firefox 48 and it works fine with the demo project [node-redis](https://github.com/francescou/docker-compose-ui/tree/master/demo-projects/node-redis)

I'm running on my machine:
- docker-compose version 1.8.0
- docker version:      1.12.1

You can see the docker-compose-ui logs with `docker logs docker-compose-ui` but, in this case, I guess it could be a client-side issue so you could open Chrome/Firefox developer tools and see the "Console" tab

could you please tell me what browser are you using and which version of docker/docker-compose/docker-compose-ui are you running? thanks

**Comment by liyaka** [comment]
I found the problem - I use environment variables in my compose file, and when I'm trying to scale from UI it fails to run since they are not set.
I saw there is another open issue on possible variables settings... At the moment, is there another option to fix it except managing env_file?

**Comment by francescou** [comment]
if I understand correctly you set environment variables and then run a docker-compose command, e.g. `version=1.2.3 docker-compose up -d` https://github.com/francescou/docker-compose-ui/issues/31#issuecomment-223508316

you need to define an environment variable in the docker-compose-ui container either using and _env_file_ or passing it as an argument, e.g. `docker run -e version=1.2.3 ...     francescou/docker-compose-ui:0.20.1`

**Comment by liyaka** [comment]
Ok, thanks.
