### ISSUE TITLE
Mounting Multiple Volumes Overwrites

### ISSUE THREAD

**Issue by centralafricabaptistcollege** [francescou/docker-compose-ui#50]
I have two mounts - one for the code and one for config. They are both local folders inside the same directory as the docker-compose.yml

``` volumes:
              - ./code:/var/www/html
              - ./code:/var/www/html/config.php
```

This works fine from the command line, but through docker-compose-ui, only the second one gets applied, even though the gui says both volumes are mounted.

**Comment by francescou** [comment]
Hi, relative paths can be a bit problematic, you could use these workarounds:
- https://github.com/dduportal/dockerfiles/issues/5#issuecomment-120488608
- https://github.com/francescou/docker-compose-ui/issues/6#issuecomment-212365603

feel free to reopen if necessary

**Comment by centralafricabaptistcollege** [comment]
Thanks. The ${PWD} seems to work great.
