### ISSUE TITLE
Is there a way to show docker-compose projects running on multiple hosts on the UI

### ISSUE THREAD

**Issue by harrybvp** [francescou/docker-compose-ui#58]
First of all thank-you so much for the awesome project

We have multiple hosts and on each hosts we are running multiple docker-compose projects.
Right now to manage these docker-compose projects . we are running docker-compose-ui instance on each host.

It would be awesome if we can manage these projects from single docker-compose UI instance.

**Comment by francescou** [comment]
thanks!

you could use a single _docker-compose-ui_ instance and connect to different remote docker hosts (see https://github.com/francescou/docker-compose-ui#remote-docker-host) or you could setup a docker swarm cluster

in both cases you are forced to use the same docker compose projects

**Comment by harrybvp** [comment]
remote-docker-host ability allows to connect to one remote docker host at a time.
i would like to configure multiple remote-docker-hosts at the same time.
Am i missing something?

**Comment by francescou** [comment]
you're right

I guess the only solution would be to setup a docker swarm cluster

**Comment by allamand** [comment]
@harrybvp I've setup a swarm cluster and compose-ui manage to see all containeurs talking to the swarm master with no problem

**Comment by francescou** [comment]
I'm closing this issue for now. Please feel free to reopen if necessary
