### ISSUE TITLE
Add option to resize log window

### ISSUE THREAD

**Issue by liyaka** [francescou/docker-compose-ui#60]
Set smaller fonts would be nice as well.
When you have a long log, it's looks almost unreadable...

Thank you!

**Comment by francescou** [comment]
I agree. A possible solution would be to display a maximized modal window.

**Comment by francescou** [comment]
I modified the CSS in 4ed4881 in order to set smaller fonts and display a maximized modal window.
There is no option to resize log window yet but it should be more readable now.

**Comment by liyaka** [comment]
Thank you! Waiting for the release

**Comment by francescou** [comment]
Hi @liyaka I've just released [v0.22.0](https://github.com/francescou/docker-compose-ui/releases/tag/v0.22.0)

**Comment by liyaka** [comment]
Thank you!
