### ISSUE TITLE
Volumes details are unreadable

### ISSUE THREAD

**Issue by liyaka** [francescou/docker-compose-ui#61]
version 0.21.0

![screen shot 2016-11-07 at 16 46 18](https://cloud.githubusercontent.com/assets/3428104/20061728/c5796934-a509-11e6-808a-9af2a97bc74c.png)

**Comment by francescou** [comment]
you can see the full path hovering the truncated volume path

**Comment by liyaka** [comment]
right, I missed that. Thanks!
Where can I see the mapping of the volume on the host?

**Comment by francescou** [comment]
you're right, there was no source mount information, fixed in 1aa9215.

I'm closing this issue for now. Please feel free to reopen if necessary

**Comment by liyaka** [comment]
Thank you!
