### ISSUE TITLE
Lost contact or Timeout with empty error

### ISSUE THREAD

**Issue by allamand** [francescou/docker-compose-ui#62]
After a while without navigate into the UI and come back, Every click on existing app or others don't provides according change. It seams that the UI have lost the connection with docker (swarm in my case).

If I make a F5 refresh I've got an empty error : 
![compose-ui-error](https://cloud.githubusercontent.com/assets/8956643/20064269/6da2ab48-a50a-11e6-8389-9924837ba7c3.png)

After that it seams to recover with the swarm connection

**Comment by francescou** [comment]
do you have any log message in the docker-compose-ui container logs?

**Comment by allamand** [comment]
can't reproduce from now I close it
