### ISSUE TITLE
Is the Kill command sending hard Termination?

### ISSUE THREAD

**Issue by PanadeEdu** [francescou/docker-compose-ui#7]
I tryed the tool, booting up my docker-compose stack was no problem. 
However the only logical way to stop my stack seems to be "kill", which sounds a bit hard. 

When terminating a Docker-Compose setup, you can sigterm it one to allow him shutdown or sigterm him twice to force hard shutdown. 
What is this tool using?

Also why not add the start/stop commands in the case you cont want to build the stack with "up"?

**Comment by francescou** [comment]
Hi Florian,

when you kill a project there is no custom signal passed to the remote Docker API, so according to the [official documentation](https://docs.docker.com/reference/api/docker_remote_api_v1.20/#kill-a-container) "SIGKILL is assumed and the call will wait for the container to exit."

I agree with you: start/stop commands could be really useful and I will add them as actions in the next release.

**Comment by PanadeEdu** [comment]
I usualy let my Containers run in active mode with plain "docker-compose up". 
I assume if you press Ctrl+C it will first try to stop them.
If you press Ctrl+C again it will kill it. 

Start/Stop should fix this issue. :)
Looking forward to it.
