### ISSUE TITLE
List of project 

### ISSUE THREAD

**Issue by allamand** [francescou/docker-compose-ui#74]
Hi @francescou,

on v1.1.0, I don't see anymore the projects in table cell, : 

![compose-ui](https://cloud.githubusercontent.com/assets/8956643/21769766/abf6fa3c-d680-11e6-8951-b8bc5c822db2.png)

Note sur if it could be Nicer if it was left-align ?

also would it be possible regarding pagination to bring at first "On" services ?

Thanks a lot for your hard work

seb

**Comment by francescou** [comment]
Hello @allamand 

maybe it could be even more useful to have a filter on active projects, I've implemented a prototype if you want to try `francescou/docker-compose-ui:filter-by-active`, feedback is welcome.

I agree with you: the new project style is a bit disorienting, so I've reverted the changes (with some slight css change)

![project list](https://cloud.githubusercontent.com/assets/1886545/21783047/fba72bd0-d6b5-11e6-97c5-1dde5252d128.png)

**Comment by francescou** [comment]
fixed in cc7b36c4f0b42995376dc068d2bc7ea3f794703e

**Comment by allamand** [comment]
Thanks @francescou this is perfect!
