### ISSUE TITLE
Docker compose run command

### ISSUE THREAD

**Issue by tarunlalwani** [francescou/docker-compose-ui#8]
Possible to dun a docker-compose run service command with current API? If not any plans to add it?

**Comment by francescou** [comment]
Hi Tarun,

this feature it's not implemented right now but I plan to add service actions soon

**Comment by francescou** [comment]
Hi, I've implemented a basic `docker run service command` functionality, check the docs:

http://francescou.github.io/docker-compose-ui/api.html#docker-compose-run-command-date-on-service-redis-of-project-node-redis

**Comment by francescou** [comment]
I will close the issue, feel free to reopen if necessary.

**Comment by MichaelMackus** [comment]
I don't think this is working any more (perhaps there was a BC break?). I'm working on fixing in my latest PR, but just wanted to post a comment since the "run_service" API endpoint definitely seems broken on my end.
