### ISSUE TITLE
Possibility to Add symlink directory

### ISSUE THREAD

**Issue by kmsundar** [francescou/docker-compose-ui#88]
In my application we almost use symlink directory. Say for example,
/home/user/projects are symlink with /var/www/html directory 
But docker-compose-ui skip the docker-compose.yml inside the symlink directory. 
Its possible to run docker-compose-ui inside symlink directory.

**Comment by francescou** [comment]
it should have been fixed in 9005a42b4e6602e95a1cd90d0e10e0e57dcfb1b6
you can use the `docker-compose-ui:latest` image until the next release

**Comment by francescou** [comment]
I've just released `francescou/docker-compose-ui:1.7.0` with `followlinks` enabled.
I'm closing this issue, feel free to reopen if necessary.
