### ISSUE TITLE
Acquiring metadata about a project

### ISSUE THREAD

**Issue by timur-han** [francescou/docker-compose-ui#9]
Hi, 

Thanks for the contribution. 

Is there anyway to view compose.yaml of a project? We cannot add additional metadata and query it using labels is that true?

**Comment by francescou** [comment]
Hi,

at the moment there is no way to view the content of the _docker-compose.yml file_.
However, I am working on a new project that will allow you to search and visualize _docker-compose.yml_ files and it will be integrated with docker-compose-ui.

Could you please explain me what you mean when you say "metadata and query it using labels is that true"?

thanks

**Comment by francescou** [comment]
not exactly what you asked, but you could get some project metadata (port mappings, volumes info) from the URL:
http://localhost:5000/api/v1/projects/hello-node
