### ISSUE TITLE
Docker Login

### ISSUE THREAD

**Issue by sylvainar** [francescou/docker-compose-ui#95]
Hey!

I'm using this project for a while now and I have to say it's pretty awesome!

One answer thought, is it possible to login on private repo (something I would do with `docker login`) ? I don't see the option anywhere and I'm experiencing troubles when I try to pull images from private repositories.

Thanks !

**Comment by sylvainar** [comment]
This is the error I have : 

`docker exception: 500 Server Error: Internal Server Error ("Get https://registry.gitlab.com/v2/sylvainar/myrepo/symfony/manifests/dev: denied: access forbidden")`

**Comment by francescou** [comment]
hello @sylvainar 
I think you could login from your docker host, than you can mount the ~/.docker volume (e.g. `docker run -v ~/.docker/:/root/.docker/:ro ... francescou/docker-compose-ui:1.8.0`)

**Comment by sylvainar** [comment]
Yeay, it works, thanks !

Note: I was about to make a PR to mention this trick in the README and it was already there… Sorry…
